Repository sopra-fs22-group-15/cozycave-server, pull requests merged in 2022-05, with the labels that each got.

#84 Feature/listing
  build.gradle
  docs/class_diagram.drawio
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/constant/ApplicationStatus.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/constant/ListingType.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/ListingController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/Picture.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/application/Application.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/listing/Listing.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/user/UserDetails.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/repository/ListingRepository.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/ListingGetDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/ListingPostDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/ListingPutDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/ListingMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ListingService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserService.java
  src/main/resources/application.properties
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserServiceTest.java
Labels: enhancement

#136 test user is not created, if user already exists
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Application.java
  src/main/resources/application.properties
Labels: bug, priority:critical

#139 documentation for /auth /listings and /users
  docs/api-v1.json
  docs/rest-api-v1.json
  docs/rest-groups-v1.json
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/listings/Listing.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ListingService.java
Labels: bug, documentation, priority:critical

#137 Feature/application/v2
  docs/api-v1.json
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/ListingController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/applications/Application.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/listings/Listing.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/repository/ApplicationRepository.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/applications/ApplicationGetDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/applications/ApplicationPostPutDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/ApplicationMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ApplicationService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ListingService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserService.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserControllerTest.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ApplicationServiceTest.java
Labels: documentation, feature, priority:critical

#142 added filters and sorting for listing and added API documentation. Re…
  docs/api-v1.json
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/ListingController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/repository/ListingRepository.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ApplicationService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ListingService.java
Labels: enhancement, feature, priority:critical, priority:high

#144 Feature/pictures
  build.gradle
  docs/api-v1.json
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Application.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/FTPUploader.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Utils.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/config/SecurityConfig.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/constant/Role.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/constant/UniversityDomains.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/AuthenticationController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/ListingController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/PictureController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/Location.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/Picture.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/applications/Application.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/listings/Listing.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/AuthenticationData.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/User.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/UserDetails.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/exceptions/GlobalExceptionAdvice.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/repository/ApplicationRepository.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/repository/ListingRepository.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/repository/PictureRepository.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/repository/UserRepository.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/AuthenticationRequestDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/LocationDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/PictureGetDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/PicturePostDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/applications/ApplicationGetDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/applications/ApplicationPostPutDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/listings/ListingGetDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/listings/ListingPostPutDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserGetDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserGetPublicDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserPostPutDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/ApplicationMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/ListingMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/PictureMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/UserMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/security/IUserDetailsService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/security/JwtAuthenticationEntryPoint.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/security/JwtAuthenticationFilter.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/security/JwtTokenProvider.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ListingService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/PictureService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserService.java
  src/main/resources/application.properties
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserControllerTest.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ApplicationServiceTest.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserServiceTest.java
Labels: documentation, enhancement, feature, priority:critical, priority:high

#145 added logic for special addresses, resolves #116
  docs/api-v1.json
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/Application.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/Picture.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/UserDetails.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/LocationDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserGetDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserPostPutDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/LocationMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserService.java
  src/main/resources/application.properties
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserControllerTest.java
Labels: documentation, enhancement, feature, priority:critical

#152 Feature/realtime collaboration
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  build.gradle
  docs/api-v1.json
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/config/SecurityConfig.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/config/WebSocketConfig.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserProfileHandler.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/UserDetails.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserGetGTDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserGetGTPublicDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/mapper/UserMapper.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/PictureService.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserService.java
Labels: bug, documentation, feature, priority:critical, priority:high, design

#154 gathertogether: docs, authorization
  docs/api-v1.json
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/config/WebSocketConfig.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserGetGTDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/dto/users/UserGetGTPublicDto.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/websockets/handler/UserProfileHandler.java
Labels: documentation, enhancement, priority:critical

#156 fix: landlords can't connect anymore
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/websockets/handler/UserProfileHandler.java
Labels: bug, priority:high

#155 Feature/search
  docs/api-v1.json
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/ListingController.java
Labels: documentation, enhancement, feature, priority:critical

#157 adding query auth to gathertogether
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/config/SecurityConfig.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/websockets/handler/UserProfileHandler.java
Labels: bug, priority:critical

#158 fix gathertogether cors
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/config/WebSocketConfig.java
Labels: bug, priority:critical

#159 Test/listings
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ApplicationService.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/ListingControllerTest.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserControllerTest.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ApplicationServiceTest.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/ListingServiceTest.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/PictureServiceTest.java
Labels: priority:critical, test

#161 added some more tests
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/ListingController.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserService.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/service/UserServiceTest.java
Labels: priority:critical, test

#162 Testing/user and auth
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserController.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/controller/UserControllerTest.java
Labels: priority:critical, test

#163 added some more stuff to the readme
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/DTOApplicationMapper.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/DTOListingMapper.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/DTOLocationMapper.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/DTOPictureMapper.java
  src/test/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/rest/DTOUserMapper.java
Labels: priority:critical, test

#164 Testing/user and auth
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/Location.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/Picture.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/listings/Listing.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/AuthenticationData.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/User.java
  src/main/java/ch/uzh/ifi/fs22/sel/group15/cozycave/server/entity/users/UserDetails.java
Labels: priority:critical, test
